version: "3"
services:
  postgis:
    image: geographica/postgis:unbiased_uakari
    ports:
      - "54322:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_PASSWD=postgres
volumes:
  db-data: