version: "3.7"

services:
  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret # TODO: Change this      
      #MYSQL_USER: test no funciona
      MYSQL_DATABASE: test
      #MYSQL_PASS: test no funciona
    ports:
        - "3307:3306"
    #command: >-
    #        --require_secure_transport=OFF
    #
    #-v
    #command: ["mysqld",
    #            "--character-set-server=utf8mb4",
    #            "--collation-server=utf8mb4_unicode_ci",
    #            "--bind-address=0.0.0.0",
    #            "--require_secure_transport=ON",
    #            "--ssl-ca=/etc/certs/root-ca.pem",
    #            "--ssl-cert=/etc/certs/server-cert.pem",
    #            "--ssl-key=/etc/certs/server-key.pem",
    #            "--default_authentication_plugin=mysql_native_password"]
    command: ["mysqld", "--bind-address=0.0.0.0"]
    #networks:
    #  - some-net
    
    volumes:
      #- my-datavolume:/var/lib/mysql
      - ./todo-mysql-data:/var/lib/mysql
      
#networks:
#  some-net:
#    driver: bridge
      
#volumes:
#  my-datavolume: